import math

print("Nul is", (4 + 4) - (4 + 4))
print("Eén is", (4 * 4) / (4 * 4))
print("Twee is", (4 * 4) / (4 + 4))
print("Drie is", math.sqrt(4 * 4) - (4 / 4))
print("Vier is", ((4 + 4) / 4) + math.sqrt(4))
print("Vijf is", (4 / 4) + (math.sqrt(4) + math.sqrt(4)))
print("Zes is", ((math.sqrt(4) + math.sqrt(4)) + 4 - math.sqrt(4)))
print("Zeven is", (4 + 4) - (4 / 4))
print("Acht is", 4 + 4 + 4 - 4)
print("Negen is", 4 + 4 + (4 / 4))
print("Tien is", 4 + 4 + 4 - math.sqrt(4))
print("Elf is", ((4 / .4) + (4 / 4)))
print("Twaalf is", (4 * 4) - math.sqrt(4) - math.sqrt(4))
print("Dertien is", math.factorial(4) / math.sqrt(4) + (4 / 4))
print("Viertien is", 4 + 4 + 4 + math.sqrt(4))
print("Vijftien is", (4 * 4) - (4 / 4))
print("Zestien is", (4 * .4) * 4 / .4)
print("Zeventien is", (4 * 4) + (4 / 4))
print("Achttien is", math.factorial(4) - math.sqrt(4) - math.sqrt(4) - math.sqrt(4))
print("Negentien is", math.factorial(4) - 4 - (4 / 4))
print("Twintig is", (4 * 4) + math.sqrt(4) + math.sqrt(4))
>>>>>>> Stashed changes
